### ISSUE TITLE
Make `fun_land` dependency optional

### ISSUE THREAD

**Issue by Qqwy** [Qqwy/elixir-tensor#9]
FunLand is quite a heavy dependency. Also, it is still not entirely stable.

Instead of annoying people with compile-time warnings and another library they might not use, I'd rather want it to become an optional dependency :slightly_smiling_face: .

**Comment by Qqwy** [comment]
This was fixed a long time ago :sweat_smile: .

**Comment by Ziinc** [comment]
Hi i get compilation warnings when installing the latest version of tensor:
```
Compiling 6 files (.ex)

== Compilation error in file lib/tensor/tensor.ex ==
** (CompileError) lib/tensor/tensor.ex:308: module FunLand.Mappable is not loaded and could not be found
    (elixir 1.10.4) expanding macro: Kernel.use/1
    lib/tensor/tensor.ex:308: Tensor.Tensor (module)
    (elixir 1.10.4) expanding macro: Kernel.if/2
    lib/tensor/tensor.ex:307: Tensor.Tensor (module)
```
